# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-C0CPAzEhUeUWtBCBCmCi138ulWgPoQ
"""

import pandas as pd, numpy as np, argparse, os
from datetime import datetime
dummy_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Revenue': [100.50, 200.75, 150.25, 300.00, None, 120.00, 180.50, '', 250.00, 100.00],
    'Date': ['2023-01-01', '2023/01/15', '10-02-2023', '2023-03-01', '2023-03-10', '2023-04-01', '2023-04-15', 'invalid_date', '2023-05-01', '2023-05-10'],
    'Status': ['Active', 'Inactive', 'Active', 'Inactive', '', 'Active', 'Inactive', 'Active', 'Inactive', 'Active']
}
dummy_df = pd.DataFrame(dummy_data)
dummy_df.to_csv('raw_data.csv', index=False)
print("Created dummy 'raw_data.csv' for execution.")
def load_data(path: str) -> pd.DataFrame:
    ext = os.path.splitext(path)[1].lower()
    if ext == ".csv":   return pd.read_csv(path, dtype=str)
    if ext == ".xlsx":  return pd.read_excel(path, dtype=str)
    raise ValueError(f"Unsupported format: {ext}")
def audit(df: pd.DataFrame) -> dict:
    return {
        "rows": len(df),
        "missing": df.isnull().sum().sum() + (df == "").sum().sum(),
        "duplicates": df.duplicated().sum(),
        "dtypes": df.dtypes.to_dict()
    }
def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    before = len(df)
    df = df.drop_duplicates()
    print(f"  [dedup] Removed {before - len(df)} duplicate rows")
    return df
def fill_missing(df: pd.DataFrame) -> pd.DataFrame:
    df["Revenue"] = pd.to_numeric(df["Revenue"], errors="coerce")
    median_rev = df["Revenue"].median()
    df["Revenue_imputed"] = df["Revenue"].isna()
    df["Revenue"] = df["Revenue"].fillna(median_rev).clip(lower=0).round(2)
    df["Name"] = df["Name"].replace("", np.nan).fillna("Unknown")
    mode_reg = df["Region"].replace("", np.nan).mode()[0]
    df["Region"] = df["Region"].replace("", np.nan).fillna(mode_reg)
    df["Status"] = df["Status"].replace("", np.nan).fillna("Inactive")
    print(f"  [fill]  Missing values handled (median revenue: ${median_rev:,.2f})")
    return df
def standardize(df: pd.DataFrame) -> pd.DataFrame:
    df["Name"]   = df["Name"].str.title()
    df["Region"] = df["Region"].str.title()
    df["Status"] = df["Status"].str.title()
    def fix_date(d):
        if not d or pd.isna(d): return None
        for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y"):
            try: return datetime.strptime(str(d).strip(), fmt).strftime("%Y-%m-%d")
            except: pass
        return None
    df["Date"] = df["Date"].apply(fix_date).fillna("2024-01-01")
    print(f"  [fmt]   Formats standardized (dates → ISO 8601, names/regions → Title Case)")
    return df
def validate(df: pd.DataFrame) -> pd.DataFrame:
    df["Revenue"] = df["Revenue"].clip(lower=0)
    valid_regions = {"North", "South", "East", "West"}
    invalid = ~df["Region"].isin(valid_regions)
    df.loc[invalid, "Region"] = "Unknown"
    print(f"  [valid] Validation complete — {invalid.sum()} invalid regions corrected")
    return df
def generate_report(df: pd.DataFrame, out_dir: str = ".") -> None:
    summary = {
        "total_revenue":  df["Revenue"].sum(),
        "avg_revenue":    df["Revenue"].mean(),
        "median_revenue": df["Revenue"].median(),
        "by_region": df.groupby("Region")["Revenue"].agg(["sum","mean","count"]).round(2),
        "by_status": df.groupby("Status")["Revenue"] .agg(["sum","mean","count"]).round(2),
    }
    print(f"\n{'='*50}")
    print(f"  AUTOMATED DATA QUALITY REPORT")
    print(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"{'='*50}")
    print(f"  Total Revenue  : ${summary['total_revenue']:>12,.2f}")
    print(f"  Avg Revenue    : ${summary['avg_revenue']:>12,.2f}")
    print(f"  Median Revenue : ${summary['median_revenue']:>12,.2f}")
    print(f"  Total Customers: {len(df):>13,}")
    print(f"\n  Revenue by Region:\n{summary['by_region'].to_string()}")
    print(f"\n  Revenue by Status:\n{summary['by_status'].to_string()}")
    out_path = os.path.join(out_dir, "cleaned_data.csv")
    df.to_csv(out_path, index=False)
    print(f"\n  ✓ Cleaned data saved: {out_path}")
def main():
    ap = argparse.ArgumentParser(description="Data Cleaning & Reporting Automation")
    ap.add_argument("--input",   default="raw_data.csv",     help="Input CSV or XLSX")
    ap.add_argument("--output",  default="cleaned_data.csv", help="Output CSV path")
    ap.add_argument("--out-dir", default=".",                help="Output directory")
    args = ap.parse_args([]) # Pass an empty list to ignore kernel arguments in Colab
    print(f"\nLoading: {args.input}")
    df = load_data(args.input)
    print("Auditing data quality…")
    before = audit(df)
    print(f"  Rows: {before['rows']:,}  |  Missing: {before['missing']}  |  Duplicates: {before['duplicates']}")
    print("\nRunning cleaning pipeline…")
    df = remove_duplicates(df)
    df = fill_missing(df)
    df = standardize(df)
    df = validate(df)
    print("\nGenerating report…")
    generate_report(df, out_dir=args.out_dir)
    print("\nDone ✓\n")
if __name__ == "__main__":
    main()